# This is the network config written by 'subiquity'
network:
  ethernets:
    eno1:
      addresses:
      - 190.160.50.11/24
      gateway4: 190.160.50.1
      nameservers:
        addresses:
        - 190.160.50.1
    eno2:
      dhcp4: false
    eno3:
      dhcp4: false
    eno4:
      dhcp4: false
  version: 2
